### ISSUE TITLE
Uncaught (in promise) RuntimeError: abort(LinkError: import object field 'L' is not a Function)

### ISSUE THREAD

**Issue by pixxelfriend** [jepiqueau/jeep-sqlite#9]
Hi, 

i am using jeep sqlite in an Vue3 setup. After upgrading from 1.3.0. to any newer version the initialisation of our database fails. 
In FF devtools i get this console output: 

`failed to asynchronously prepare wasm: LinkError: import object field 'L' is not a Function [jeep-sqlite.entry.js:2650]

(webpack://projectname/node_modules/jeep-sqlite/dist/esm/jeep-sqlite.entry.js?41d6)
LinkError: import object field 'L' is not a Function [jeep-sqlite.entry.js:2591]

Uncaught (in promise) RuntimeError: abort(LinkError: import object field 'L' is not a Function). Build with -s ASSERTIONS=1 for more info. [jeep-sqlite.entry.js:2591]` 

It seems db.open is not working anymore. "DB opened" is never called. 

```
db = await createOrRetrieveConnection(sqlite, 'dbname')
                console.log('got DB connection', db)
                const ret = await db.isDBOpen()
                if (!ret.result) {
                    await db.open()
                    console.log('DB opened')
}
```

**Comment by jepiqueau** [comment]
@pixxelfriend remove the sql-wasm.wasm file from the public/assets  of your app. Install the latest release of jeep-sqlite and copy the wasm file from node_modules/sql.js/dist to the public/assets  folder of your app and rebuild

**Comment by pixxelfriend** [comment]
Thanks, it works great!
